# Generated by Django 3.2.13 on 2022-05-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('title', models.CharField(max_length=150)),
                ('slug', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('publishAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
